[package]
name = "EternalBlue_rs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "eternalblue_rs"
path = "src/main.rs"

[dependencies]
aes = "0.8.4"
rand = "0.9.1"
rsa = { version = "0.9.2", features = ["pem"] }
